#!/bin/bash

# Simple wrapper script to control MPD

# Get the codes, stored in variable $MPC
source codes.bash
#OPTIONS="[%position%] %albumartist% - %title%"
OPTIONS="[%position%] %artist% - %title%"

HELP="Arguments are:\n
  play         : Play the current playlist (default)\n
  pause        : Pause the song if playing\n
  next         : Go to the next song\n
  prev         : Go to the previous song\n
  toggle       : Switch between play and pause\n
  list         : Show the current playlist\n
  volume_down  : Turn down the volume by 2%\n
  volume_up    : Turn up the volume by 2%\n
  volume_max   : Set the volume to max 100%\n
  random       : Play a random album\n
  shuffle      : Shuffle the current playlist\n
  favorite     : Play a favorite album"

# Only allow a single argument
ARG=""
if [[ $# > 1 ]]
then
  echo -e $HELP
  exit 2
elif [[ $# == 1 ]]
then
  ARG=$1
fi

# Check the command
if [[ $ARG == "" || $ARG == "play" ]]
then
  $MPC play
elif [[ $ARG == "pause" ]]
then
  $MPC pause
elif [[ $ARG == "next" ]]
then
  $MPC next
elif [[ $ARG == "prev" ]]
then
  $MPC prev
elif [[ $ARG == "toggle" ]]
then
  $MPC toggle
elif [[ $ARG == "list" ]]
then
  $MPC
elif [[ $ARG == "volume_down" ]]
then
  $MPC volume -2
elif [[ $ARG == "volume_up" ]]
then
  $MPC volume +2
elif [[ $ARG == "volume_max" ]]
then
  $MPC volume 100
elif [[ $ARG == "random" ]]
then
  ALBUM=`$MPC list album | sort -R | head -n1`
  if [[ $ALBUM != "" ]]
  then
    echo -e "[$ALBUM]\n"
    $MPC clear -q
    $MPC findadd album "$ALBUM"
  else
    echo "Failed to find album."
  fi
elif [[ $ARG == "shuffle" ]]
then
  $MPC shuffle
elif [[ $ARG == "favorite" ]]
then
  FAVORITES="Absolution|Blue Sky Noise|Burst and Bloom EP|Carnavas|Commit This To Memory|Days of the New|Deja Entendu|Good Apollo I'm Burning Star IV, Volume One|I Am the Movie|IX|In Keeping Secrets of Silent Earth: 3|Juturna|Keep It Like a Secret|Lateralus|Make Up the Breakdown|Morning View|Now Here Is Nowhere|On Letting Go|Pinkerton|Satori|Separation|Source Tags|Songs for the Deaf|Swoon|The Color Before the Sun|The Colour and the Shape|The Devil and God Are Raging Inside Me|The Things We Think We're Missing|The Ugly Organ|There's Nothing Wrong With Love|Turn On the Bright Lights|Wiretap Scars"
  ALBUM=`$MPC list album | egrep "$FAVORITES" | sort -R | head -n1`
  if [[ $ALBUM != "" ]]
  then
    echo -e "[$ALBUM]\n"
    $MPC clear -q
    $MPC findadd album "$ALBUM"
  else
    echo "Failed to find album."
  fi
else
  echo -e $HELP
  exit 2
fi

# Run a few more commands
$MPC -f "$OPTIONS" playlist
echo
$MPC
exit $?
